name: RAE Movies Continuous Integration
run-name: ${{ github.actor }} is running CI on RAE Movies 🚀
on:
  pull_request:
    branches:
      - '**'
jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set Node.js 20.x
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'
      - run: yarn install
      - run: yarn lint
      - run: yarn type-check